// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file civil/tiles/v1/tiles.proto (package civil.tiles.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../google/api/annotations_pb";

/**
 * Describes the file civil/tiles/v1/tiles.proto.
 */
export const file_civil_tiles_v1_tiles = /*@__PURE__*/
  fileDesc("ChpjaXZpbC90aWxlcy92MS90aWxlcy5wcm90bxIOY2l2aWwudGlsZXMudjEiKQoSR2V0VGlsZUpzb25SZXF1ZXN0EhMKC3NvdXJjZV9uYW1lGAEgASgJIs8BChNHZXRUaWxlSnNvblJlc3BvbnNlEhAKCHRpbGVqc29uGAEgASgJEgwKBG5hbWUYAiABKAkSEwoLZGVzY3JpcHRpb24YAyABKAkSDQoFdGlsZXMYBCADKAkSDwoHbWluem9vbRgFIAEoBRIPCgdtYXh6b29tGAYgASgFEg4KBmJvdW5kcxgHIAMoARIOCgZjZW50ZXIYCCADKAESMgoNdmVjdG9yX2xheWVycxgJIAMoCzIbLmNpdmlsLnRpbGVzLnYxLlZlY3RvckxheWVyIrgBCgtWZWN0b3JMYXllchIKCgJpZBgBIAEoCRITCgtkZXNjcmlwdGlvbhgCIAEoCRIPCgdtaW56b29tGAMgASgFEg8KB21heHpvb20YBCABKAUSNwoGZmllbGRzGAUgAygLMicuY2l2aWwudGlsZXMudjEuVmVjdG9yTGF5ZXIuRmllbGRzRW50cnkaLQoLRmllbGRzRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4ASJGCg5HZXRUaWxlUmVxdWVzdBITCgtzb3VyY2VfbmFtZRgBIAEoCRIJCgF6GAIgASgFEgkKAXgYAyABKAUSCQoBeRgEIAEoBSI1Cg9HZXRUaWxlUmVzcG9uc2USFAoMY29udGVudF90eXBlGAEgASgJEgwKBGRhdGEYAiABKAwy+QEKC1RpbGVTZXJ2aWNlEnQKC0dldFRpbGVKc29uEiIuY2l2aWwudGlsZXMudjEuR2V0VGlsZUpzb25SZXF1ZXN0GiMuY2l2aWwudGlsZXMudjEuR2V0VGlsZUpzb25SZXNwb25zZSIcgtPkkwIWEhQvdGlsZXMve3NvdXJjZV9uYW1lfRJ0CgdHZXRUaWxlEh4uY2l2aWwudGlsZXMudjEuR2V0VGlsZVJlcXVlc3QaHy5jaXZpbC50aWxlcy52MS5HZXRUaWxlUmVzcG9uc2UiKILT5JMCIhIgL3RpbGVzL3tzb3VyY2VfbmFtZX0ve3p9L3t4fS97eX1CtQEKEmNvbS5jaXZpbC50aWxlcy52MUIKVGlsZXNQcm90b1ABWjlnaXRodWIuY29tL2NpdmlsLWxhYnMvY2l2aWwtYXBpLWdvL2NpdmlsL3RpbGVzL3YxO3RpbGVzdjGiAgNDVFiqAg5DaXZpbC5UaWxlcy5WMcoCDkNpdmlsXFRpbGVzXFYx4gIaQ2l2aWxcVGlsZXNcVjFcR1BCTWV0YWRhdGHqAhBDaXZpbDo6VGlsZXM6OlYxYgZwcm90bzM", [file_google_api_annotations]);

/**
 * Describes the message civil.tiles.v1.GetTileJsonRequest.
 * Use `create(GetTileJsonRequestSchema)` to create a new message.
 */
export const GetTileJsonRequestSchema = /*@__PURE__*/
  messageDesc(file_civil_tiles_v1_tiles, 0);

/**
 * Describes the message civil.tiles.v1.GetTileJsonResponse.
 * Use `create(GetTileJsonResponseSchema)` to create a new message.
 */
export const GetTileJsonResponseSchema = /*@__PURE__*/
  messageDesc(file_civil_tiles_v1_tiles, 1);

/**
 * Describes the message civil.tiles.v1.VectorLayer.
 * Use `create(VectorLayerSchema)` to create a new message.
 */
export const VectorLayerSchema = /*@__PURE__*/
  messageDesc(file_civil_tiles_v1_tiles, 2);

/**
 * Describes the message civil.tiles.v1.GetTileRequest.
 * Use `create(GetTileRequestSchema)` to create a new message.
 */
export const GetTileRequestSchema = /*@__PURE__*/
  messageDesc(file_civil_tiles_v1_tiles, 3);

/**
 * Describes the message civil.tiles.v1.GetTileResponse.
 * Use `create(GetTileResponseSchema)` to create a new message.
 */
export const GetTileResponseSchema = /*@__PURE__*/
  messageDesc(file_civil_tiles_v1_tiles, 4);

/**
 * @generated from service civil.tiles.v1.TileService
 */
export const TileService = /*@__PURE__*/
  serviceDesc(file_civil_tiles_v1_tiles, 0);

