// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file civil/parcels/v1/parcels.proto (package civil.parcels.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb";
import { file_gnostic_openapi_v3_annotations } from "../../../gnostic/openapi/v3/annotations_pb";
import { file_google_protobuf_struct } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file civil/parcels/v1/parcels.proto.
 */
export const file_civil_parcels_v1_parcels = /*@__PURE__*/
  fileDesc("Ch5jaXZpbC9wYXJjZWxzL3YxL3BhcmNlbHMucHJvdG8SEGNpdmlsLnBhcmNlbHMudjEikQEKHFVwZGF0ZVBhcmNlbEF0dHJpYnV0ZVJlcXVlc3QSKAoKcGFyY2VsX2lkcxgBIAMoCUIUukgRkgEOCAEQ6AciB3IFEAEYgAISIgoOYXR0cmlidXRlX25hbWUYAiABKAlCCrpIB3IFEAEYgAISIwoPYXR0cmlidXRlX3ZhbHVlGAMgASgJQgq6SAdyBRABGIACIh8KHVVwZGF0ZVBhcmNlbEF0dHJpYnV0ZVJlc3BvbnNlIjEKEEdldFBhcmNlbFJlcXVlc3QSHQoJcGFyY2VsX2lkGAEgASgJQgq6SAdyBRABGIACIkQKEUdldFBhcmNlbFJlc3BvbnNlEi8KDnBhcmNlbF9kZXRhaWxzGAEgASgLMhcuZ29vZ2xlLnByb3RvYnVmLlN0cnVjdCJeChlHZXRQYXJjZWxBdHRyaWJ1dGVSZXF1ZXN0Eh0KCXBhcmNlbF9pZBgBIAEoCUIKukgHcgUQARiAAhIiCg5hdHRyaWJ1dGVfbmFtZRgCIAEoCUIKukgHcgUQARiAAiJBChpHZXRQYXJjZWxBdHRyaWJ1dGVSZXNwb25zZRIjCg9hdHRyaWJ1dGVfdmFsdWUYAyABKAlCCrpIB3IFEAEYgAIy1gIKDVBhcmNlbFNlcnZpY2USegoVVXBkYXRlUGFyY2VsQXR0cmlidXRlEi4uY2l2aWwucGFyY2Vscy52MS5VcGRhdGVQYXJjZWxBdHRyaWJ1dGVSZXF1ZXN0Gi8uY2l2aWwucGFyY2Vscy52MS5VcGRhdGVQYXJjZWxBdHRyaWJ1dGVSZXNwb25zZSIAElYKCUdldFBhcmNlbBIiLmNpdmlsLnBhcmNlbHMudjEuR2V0UGFyY2VsUmVxdWVzdBojLmNpdmlsLnBhcmNlbHMudjEuR2V0UGFyY2VsUmVzcG9uc2UiABJxChJHZXRQYXJjZWxBdHRyaWJ1dGUSKy5jaXZpbC5wYXJjZWxzLnYxLkdldFBhcmNlbEF0dHJpYnV0ZVJlcXVlc3QaLC5jaXZpbC5wYXJjZWxzLnYxLkdldFBhcmNlbEF0dHJpYnV0ZVJlc3BvbnNlIgBCswMKFGNvbS5jaXZpbC5wYXJjZWxzLnYxQgxQYXJjZWxzUHJvdG9QAVo9Z2l0aHViLmNvbS9jaXZpbC1sYWJzL2NpdmlsLWFwaS1nby9jaXZpbC9wYXJjZWxzL3YxO3BhcmNlbHN2MaICA0NQWKoCEENpdmlsLlBhcmNlbHMuVjHKAhBDaXZpbFxQYXJjZWxzXFYx4gIcQ2l2aWxcUGFyY2Vsc1xWMVxHUEJNZXRhZGF0YeoCEkNpdmlsOjpQYXJjZWxzOjpWMbpH6gESnwEKCUNpdmlsIEFQSRKKAUFQSSBkZXNjcmlwdGlvbiBmb3IgdGhlIENpdmlsIHBsYXRmb3JtLiBBdXRoIHRva2VuIGNhbiBiZSByZXRyaWV2ZWQgYnkgcHJlZml4aW5nICJhdXRoLSIgdG8gdGhlIGJlZ2lubmluZyBvZiB5b3VyIGp1cmlzZGljdGlvbidzIGVuZHBvaW50LjIFMC4wLjEaHQobaHR0cHM6Ly9sZWVwYS5jaXZpbGxhYnMuYXBwKic6JQojCgpCZWFyZXJBdXRoEhUKEwoEaHR0cCoGYmVhcmVyMgNKV1RiBnByb3RvMw", [file_buf_validate_validate, file_gnostic_openapi_v3_annotations, file_google_protobuf_struct]);

/**
 * Describes the message civil.parcels.v1.UpdateParcelAttributeRequest.
 * Use `create(UpdateParcelAttributeRequestSchema)` to create a new message.
 */
export const UpdateParcelAttributeRequestSchema = /*@__PURE__*/
  messageDesc(file_civil_parcels_v1_parcels, 0);

/**
 * Describes the message civil.parcels.v1.UpdateParcelAttributeResponse.
 * Use `create(UpdateParcelAttributeResponseSchema)` to create a new message.
 */
export const UpdateParcelAttributeResponseSchema = /*@__PURE__*/
  messageDesc(file_civil_parcels_v1_parcels, 1);

/**
 * Describes the message civil.parcels.v1.GetParcelRequest.
 * Use `create(GetParcelRequestSchema)` to create a new message.
 */
export const GetParcelRequestSchema = /*@__PURE__*/
  messageDesc(file_civil_parcels_v1_parcels, 2);

/**
 * Describes the message civil.parcels.v1.GetParcelResponse.
 * Use `create(GetParcelResponseSchema)` to create a new message.
 */
export const GetParcelResponseSchema = /*@__PURE__*/
  messageDesc(file_civil_parcels_v1_parcels, 3);

/**
 * Describes the message civil.parcels.v1.GetParcelAttributeRequest.
 * Use `create(GetParcelAttributeRequestSchema)` to create a new message.
 */
export const GetParcelAttributeRequestSchema = /*@__PURE__*/
  messageDesc(file_civil_parcels_v1_parcels, 4);

/**
 * Describes the message civil.parcels.v1.GetParcelAttributeResponse.
 * Use `create(GetParcelAttributeResponseSchema)` to create a new message.
 */
export const GetParcelAttributeResponseSchema = /*@__PURE__*/
  messageDesc(file_civil_parcels_v1_parcels, 5);

/**
 * @generated from service civil.parcels.v1.ParcelService
 */
export const ParcelService = /*@__PURE__*/
  serviceDesc(file_civil_parcels_v1_parcels, 0);

