// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file civil/parcels/v1/parcels.proto (package civil.parcels.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file civil/parcels/v1/parcels.proto.
 */
export declare const file_civil_parcels_v1_parcels: GenFile;

/**
 * @generated from message civil.parcels.v1.UpdateParcelAttributeRequest
 */
export declare type UpdateParcelAttributeRequest = Message<"civil.parcels.v1.UpdateParcelAttributeRequest"> & {
  /**
   * @generated from field: repeated string parcel_ids = 1;
   */
  parcelIds: string[];

  /**
   * @generated from field: string attribute_name = 2;
   */
  attributeName: string;

  /**
   * @generated from field: string attribute_value = 3;
   */
  attributeValue: string;
};

/**
 * Describes the message civil.parcels.v1.UpdateParcelAttributeRequest.
 * Use `create(UpdateParcelAttributeRequestSchema)` to create a new message.
 */
export declare const UpdateParcelAttributeRequestSchema: GenMessage<UpdateParcelAttributeRequest>;

/**
 * @generated from message civil.parcels.v1.UpdateParcelAttributeResponse
 */
export declare type UpdateParcelAttributeResponse = Message<"civil.parcels.v1.UpdateParcelAttributeResponse"> & {
};

/**
 * Describes the message civil.parcels.v1.UpdateParcelAttributeResponse.
 * Use `create(UpdateParcelAttributeResponseSchema)` to create a new message.
 */
export declare const UpdateParcelAttributeResponseSchema: GenMessage<UpdateParcelAttributeResponse>;

/**
 * @generated from service civil.parcels.v1.ParcelService
 */
export declare const ParcelService: GenService<{
  /**
   * Updates a specified attribute for one or more parcels, identified by their parcel IDs.
   *
   * @generated from rpc civil.parcels.v1.ParcelService.UpdateParcelAttribute
   */
  updateParcelAttribute: {
    methodKind: "unary";
    input: typeof UpdateParcelAttributeRequestSchema;
    output: typeof UpdateParcelAttributeResponseSchema;
  },
}>;

