// @generated by protoc-gen-es v2.11.0 with parameter "target=js+dts"
// @generated from file civil/parcels/v1/parcels.proto (package civil.parcels.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { JsonObject, Message } from "@bufbuild/protobuf";

/**
 * Describes the file civil/parcels/v1/parcels.proto.
 */
export declare const file_civil_parcels_v1_parcels: GenFile;

/**
 * @generated from message civil.parcels.v1.UpdateParcelsAttributeRequest
 */
export declare type UpdateParcelsAttributeRequest = Message<"civil.parcels.v1.UpdateParcelsAttributeRequest"> & {
  /**
   * @generated from field: repeated string parcel_ids = 1;
   */
  parcelIds: string[];

  /**
   * @generated from field: string attribute_name = 2;
   */
  attributeName: string;

  /**
   * @generated from field: string attribute_value = 3;
   */
  attributeValue: string;
};

/**
 * Describes the message civil.parcels.v1.UpdateParcelsAttributeRequest.
 * Use `create(UpdateParcelsAttributeRequestSchema)` to create a new message.
 */
export declare const UpdateParcelsAttributeRequestSchema: GenMessage<UpdateParcelsAttributeRequest>;

/**
 * @generated from message civil.parcels.v1.UpdateParcelsAttributeResponse
 */
export declare type UpdateParcelsAttributeResponse = Message<"civil.parcels.v1.UpdateParcelsAttributeResponse"> & {
};

/**
 * Describes the message civil.parcels.v1.UpdateParcelsAttributeResponse.
 * Use `create(UpdateParcelsAttributeResponseSchema)` to create a new message.
 */
export declare const UpdateParcelsAttributeResponseSchema: GenMessage<UpdateParcelsAttributeResponse>;

/**
 * @generated from message civil.parcels.v1.GetParcelRequest
 */
export declare type GetParcelRequest = Message<"civil.parcels.v1.GetParcelRequest"> & {
  /**
   * @generated from field: string parcel_id = 1;
   */
  parcelId: string;
};

/**
 * Describes the message civil.parcels.v1.GetParcelRequest.
 * Use `create(GetParcelRequestSchema)` to create a new message.
 */
export declare const GetParcelRequestSchema: GenMessage<GetParcelRequest>;

/**
 * @generated from message civil.parcels.v1.GetParcelResponse
 */
export declare type GetParcelResponse = Message<"civil.parcels.v1.GetParcelResponse"> & {
  /**
   * @generated from field: google.protobuf.Struct parcel_attributes = 1;
   */
  parcelAttributes?: JsonObject;
};

/**
 * Describes the message civil.parcels.v1.GetParcelResponse.
 * Use `create(GetParcelResponseSchema)` to create a new message.
 */
export declare const GetParcelResponseSchema: GenMessage<GetParcelResponse>;

/**
 * @generated from message civil.parcels.v1.GetParcelAttributeRequest
 */
export declare type GetParcelAttributeRequest = Message<"civil.parcels.v1.GetParcelAttributeRequest"> & {
  /**
   * @generated from field: string parcel_id = 1;
   */
  parcelId: string;

  /**
   * @generated from field: string attribute_name = 2;
   */
  attributeName: string;
};

/**
 * Describes the message civil.parcels.v1.GetParcelAttributeRequest.
 * Use `create(GetParcelAttributeRequestSchema)` to create a new message.
 */
export declare const GetParcelAttributeRequestSchema: GenMessage<GetParcelAttributeRequest>;

/**
 * @generated from message civil.parcels.v1.GetParcelAttributeResponse
 */
export declare type GetParcelAttributeResponse = Message<"civil.parcels.v1.GetParcelAttributeResponse"> & {
  /**
   * @generated from field: string attribute_value = 3;
   */
  attributeValue: string;
};

/**
 * Describes the message civil.parcels.v1.GetParcelAttributeResponse.
 * Use `create(GetParcelAttributeResponseSchema)` to create a new message.
 */
export declare const GetParcelAttributeResponseSchema: GenMessage<GetParcelAttributeResponse>;

/**
 * @generated from message civil.parcels.v1.GetParcelAttributesRequest
 */
export declare type GetParcelAttributesRequest = Message<"civil.parcels.v1.GetParcelAttributesRequest"> & {
  /**
   * @generated from field: string parcel_id = 1;
   */
  parcelId: string;

  /**
   * @generated from field: repeated string attribute_names = 2;
   */
  attributeNames: string[];
};

/**
 * Describes the message civil.parcels.v1.GetParcelAttributesRequest.
 * Use `create(GetParcelAttributesRequestSchema)` to create a new message.
 */
export declare const GetParcelAttributesRequestSchema: GenMessage<GetParcelAttributesRequest>;

/**
 * @generated from message civil.parcels.v1.GetParcelAttributesResponse
 */
export declare type GetParcelAttributesResponse = Message<"civil.parcels.v1.GetParcelAttributesResponse"> & {
  /**
   * @generated from field: google.protobuf.Struct parcel_attributes = 1;
   */
  parcelAttributes?: JsonObject;
};

/**
 * Describes the message civil.parcels.v1.GetParcelAttributesResponse.
 * Use `create(GetParcelAttributesResponseSchema)` to create a new message.
 */
export declare const GetParcelAttributesResponseSchema: GenMessage<GetParcelAttributesResponse>;

/**
 * @generated from service civil.parcels.v1.ParcelsService
 */
export declare const ParcelsService: GenService<{
  /**
   * Updates a specified attribute for one or more parcels, identified by their parcel IDs.
   *
   * @generated from rpc civil.parcels.v1.ParcelsService.UpdateParcelsAttribute
   */
  updateParcelsAttribute: {
    methodKind: "unary";
    input: typeof UpdateParcelsAttributeRequestSchema;
    output: typeof UpdateParcelsAttributeResponseSchema;
  },
  /**
   * Retrieves all a specified parcel's attributes as an object.
   *
   * @generated from rpc civil.parcels.v1.ParcelsService.GetParcel
   */
  getParcel: {
    methodKind: "unary";
    input: typeof GetParcelRequestSchema;
    output: typeof GetParcelResponseSchema;
  },
  /**
   * Retrieves a specified attribute value for a given parcel.
   *
   * @generated from rpc civil.parcels.v1.ParcelsService.GetParcelAttribute
   */
  getParcelAttribute: {
    methodKind: "unary";
    input: typeof GetParcelAttributeRequestSchema;
    output: typeof GetParcelAttributeResponseSchema;
  },
  /**
   * Retrieves specificied attributes about a parcel as an object.
   *
   * @generated from rpc civil.parcels.v1.ParcelsService.GetParcelAttributes
   */
  getParcelAttributes: {
    methodKind: "unary";
    input: typeof GetParcelAttributesRequestSchema;
    output: typeof GetParcelAttributesResponseSchema;
  },
}>;

